export const IMAGES = {
  OnboardingBg: require('../assets/images/OnboardingBg.png'),
  Decoration: require('../assets/images/Decoration.png'),
  streak: require('../assets/images/streak.png'),
  questionImg: require('../assets/images/QuestionImage.png'),
  RAText: require('../assets/images/RAText.png'),
  streakBg: require('../assets/images/streakBg.png'),
};

export const icons = {
  hamburger: require('../assets/icons/Hamburger.png'),
  share: require('../assets/icons/share.png'),
  shareLink: require('../assets/icons/shareLink.png'),
  heart: require('../assets/icons/heart.png'),
  leftarrow: require('../assets/icons/LeftArrow.png'),
  rightarrow: require('../assets/icons/RightArrow.png'),
  submit: require('../assets/icons/SubmitButton.png'),
  tick: require('../assets/icons/tick.png'),
  questionTick: require('../assets/icons/questionTick.png'),
  cross: require('../assets/icons/cross.png'),
  help: require('../assets/icons/help.png'),
  statistics: require('../assets/icons/statistics.png'),
  previous: require('../assets/icons/previous.png'),
  question: require('../assets/icons/question.png'),
  pro: require('../assets/icons/Pro.png'),
  setting: require('../assets/icons/settings.png'),
  back: require('../assets/icons/back.png'),
  streak: require('../assets/icons/streak.png'),
  cg: require('../assets/icons/cg.png'),
  greentick: require('../assets/icons/greentick.png'),
  greytick: require('../assets/icons/greytick.png'),
  redcross: require('../assets/icons/redcross.png'),
  lock: require('../assets/icons/lock.png'),
  AppIcon: require('../assets/icons/AppIcon.png'),
};
